# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-TS241JEpZX9_9eKUZRdjtfUHpRSyG
"""

"""
EX 001  Boas-vindas Personalizadas: Crie uma variável para armazenar o nome de
uma pessoa. Peça para o usuário digitar seu nome, armazene-o e depois exiba a
mensagem: "Olá [nome], seja bem-vindo!"
"""
print("===== Boas-vindas Personalizadas: =====\n")
nome = input("Digite o seu nome: ")
print(f"Olá {nome}, seja bem-vindo!\n\n")

"""
EX 002 Endereço Completo: Crie três variáveis: cidade, estado e cep. Peça ao
usuário para preencher cada uma e, ao final, exiba o endereço formatado em
uma única linha.
"""
print("===== Endereço Completo: =====\n")
cidade = input("Digite a sua Cidade: ")
estado = input("Digite o seu Estado: ")
cep = input("Digite o seu Cep: ")
print(f"Você mora em {cidade}, Estado de {estado}, no Cep {cep}\n\n")

"""
EX 003 Soma de Dois Números: Receba dois números inteiros do usuário,
armazeneos em variáveis distintas, calcule a soma e exiba o resultado.
"""
print("===== Soma de Dois Números: =====\n")
n1 = int(input("Digite um valor inteiro: "))
n2 = int(input("Digite outro valor inteiro: "))
print(f"A soma entre {n1} + {n2} = {n1 + n2}\n\n")

"""
EX 004 Calculadora de Idade: Crie uma variável para o ano_nascimento e outra para
o ano_atual. Peça os dados ao usuário, subtraia as variáveis e exiba: "Sua
idade é ou será [resultado] anos".
"""
print("===== Calculadora de Idade: =====\n")
ano_nascimento = int(input("Digite o ano do seu nascimento: "))
ano_atual = int(input("Digite o ano atual: "))
print(f"Sua idade é ou será {ano_atual - ano_nascimento} anos\n\n")

"""
Ex 005 Desafio Calculadora de Gorjeta: * Receba o valor total da conta de um
restaurante. Receba a porcentagem de gorjeta que o cliente deseja deixar (ex:
10, 15 ou 20).
Calcule o valor da gorjeta e o valor total final (conta + gorjeta).
Exiba os dois valores separadamente.
"""
print("===== Desafio Calculadora de Gorjeta: =====\n")
conta = float(input("Digite o valor total da conta: "))
gorjeta = float(input("Digite o percentual que gostaria de ofertar como gorjeta: "))
gorjeta = (gorjeta * conta) / 100
print(f"\nValor final da conta fica em R$:{conta + gorjeta} \nsendo R$:{conta} do consmo no local \ne R$:{gorjeta} de gorjeta ofertada!")

"""
Exercício 1 – Cadastro interativo
Crie um programa que:
• Pergunte o nome do aluno
• Pergunte a idade
• Pergunte se está matriculado (True ou False)
• Mostre tudo organizado na tela
"""
print("===== Cadastro interativo: =====\n")

aluno = input("Digite o nome do Aluno: ")
idade = int(input("Digite a idade do Aluno: "))
matricula = bool(input("O aluno esta matriculado? (True -> Sim), (False -> Não): "))

if matricula:
  print(f"Aluno {aluno}, com idade de {idade} anos, com matricula ativa\n\n")
else:
  print(f"Aluno {aluno}, com idade de {idade} anos, se encontra na fila de espera\n\n")

"""
Exercício 2 – Ano de nascimento
O programa deve:
• Perguntar o nome
• Perguntar o ano de nascimento
• Usar o ano atual como constante
• Calcular e mostrar a idade
"""
print("===== Ano de nascimento: =====\n")

from datetime import date
nome = input("Digite o seu nome: ")
nascimento = int(input("Digite o ano do seu nascimento: "))
ATUAL = date.today().year

print(f"Você tem o terá {ATUAL - nascimento} anos \n\n")

"""
Exercício 3 – Calculadora com input
Peça dois números ao usuário e mostre:
• Soma
• Subtração
• Multiplicação
• Divisão
"""
print("===== Calculadora com input: =====\n")

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))

print(f"A soma entre {n1} + {n2} = {n1 + n2}")
print(f"A subtração entre {n1} - {n2} = {n1 - n2}")
print(f"A Multiplicação entre {n1} X {n2} = {n1 * n2}")
print(f"A divisão entre {n1} / {n2} = {n1 / n2} \n\n")

"""
Exercício 4 – Número Par
Peça um número inteiro e verifique se ele é:
• Par
"""
print("===== Número Par: =====\n")

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
  print(f"O número {numero} é par \n\n")
else:
  print(f"O número {numero} é impar \n\n")

"""
Exercício 5 – Divisão inteira explicada
Peça dois números e mostre:
• Divisão inteira
• Resto da divisão
• Explique com comentários no código.
"""
print("===== Divisão inteira explicada: =====\n")

#Entrada dos valores para a realização dos calculos
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

#A divisaõ inteira utiliza somente a parte inteira do número (a esquerda da virgula)
print(f"A divisão inteira entre {numero1} e {numero2} = {numero1 // numero2}")

#O resto da disão são as casas decimais apos a virgula (a direita da virgula)
print(f"O resto da divisão entre {numero1} e {numero2} = {numero1 % numero2} \n\n")

"""
Exercício 6 – Maior de idade
Nessa exercício pergunte a idade e mostre se a pessoa é maior de
idade
"""
print("===== Maior idade: =====\n")

idade = int(input("Digite a sua idade: "))

if idade >= 18:
  print(f"Você possui {idade} anos, portanto possui maior idade\n\n")
else:
  print(f"Você possui {idade} anos, portanto possui menor idade\n\n")

"""
Exercício 7 – Média do aluno
Peça:
• Duas notas
• Calcule a média e diga se o aluno está aprovado (média ≥ 7).
"""
print("===== Média d aluno: =====\n")

nota1 = float(input("Digite a primeira nota obtida: "))
nota2 = float(input("Digite a segunda nota obtida: "))
media = (nota1 + nota2) / 2

if media >= 7:
  print(f"Parabens, você atingiu o criterio minimo de média 7, portanto foi aprovado com nota {media}\n\n")
else:
  print(f"Infelismente você não atingiu o critério minimo de nota 7, portanto esta de recuperação por ter obtido nota {media}\n\n")

"""
Exercício 8 – Acesso ao sistema
Pergunte ao usuário:
• Se está logado
• Se é administrador
• Verifique se ele pode acessar o sistema.
"""
print("===== Acesso ao sistema: =====\n")

login = input("Você está logado no sistema? (sim / não): ")
admin = input("Você possui nivel administrador? (sim / não): ")

if login == "sim" or login == "Sim" or login == "SIM":
  if admin == "sim" or admin == "Sim" or admin == "SIM":
    print("Acesso concediddo com sucesso!!\n\n")
else:
  print("Acesso negado, por hierarquia de nivel ou falta de login\n\n")

"""
Exercício 10 – Desafio final
Crie um programa que:
• Pergunte:
• Nome do aluno
• Idade
• Três notas
• Calcule a média
• Verifique:
• Se é maior de idade
• Se a média é par ou ímpar
• Se está aprovado (média ≥ 7)
• Mostre tudo organizado na tela
"""
print("===== Desafio Final: =====/n")

nome_aluno = input("Digite o nome do aluno: ")
idade = int(input("Digite a idade: "))
nota1 = float(input("Informe a primeira nota obtida: "))
nota2 = float(input("Informe a segunda nota obtida: "))
nota3 = float(input("Informe a terceira nota obtida: "))
media = (nota1 + nota2 + nota3) / 3

print("\n_______ Processando... ... ... \n")

if idade >= 18:
  print(f"O aluno(a) {nome_aluno} ja possui a maior idade")
else:
  print(f"O aluno(a) {nome_aluno} Não possui a maio idade")

if media % 2 == 0:
  print(f"A média final do aluno(a) {nome_aluno} é par")
else:
  print(f"A média final do aluno(a) {nome_aluno} é impar")

if media >= 7:
  print(f"Parabens {nome_aluno} você foi aprovado com nota {media}")
else:
  print(f"Não foi desta vez {nome_aluno}, você obteve média final de {media} e a nossa tolerancia é de 7.00, portanto esta de recuperação")

"""
1. Crie um programa que tenha uma função que:
Receba dois números
Retorne o maior deles.
"""
def maior_numero(numero_1, numero_2):
  if numero_1 > numero_2 :
    return numero_1
  elif numero_2 > numero_1 :
    return numero_2
  else:
    return print("\nOs valores são identicos!\n")

print("===== Maior Número ===== \n")

n1 = float(input("Digite o primeiro valor: "))
n2 = float(input("Digite o segundo valor: "))

if n1 != n2:
  print(f"\nO Maior número é {maior_numero(n1, n2)}\n")
else:
  maior_numero(n1, n2)

"""
2. Crie um programa, cuja função:
Receba um valor em Reais
Retorne o valor com 15% de imposto.
"""
def imposto (valor):
  valor = valor * 1.15
  return valor

print("===== Calculadora de Imposto: =====\n")

reais = float(input("Digite o valor a ser declarado: "))

print(f"Com o valor de R:{reais:.2f} + o imposto passara a a ser R$:{imposto(reais):.2f}\n")

"""
3. Crie um programa que tenha:
Uma função para calcular o IMC
Uma função para classificar o IMC
Usar as duas funções e retornar ao usuário tanto o valor de IMC e a
categoria.
"""
def calculo_imc(peso, altura):
    imc = peso / (altura ** 2)
    return imc

def classificacao_imc(imc):
    if imc < 18.5:
        return "Classificação: Baixo peso, Risco de doenças: Alto"
    elif 18.5 <= imc <= 24.9:
        return "Classificação: Peso Normal, Risco de doenças: Baixo"
    elif 25 <= imc <= 29.9:
        return "Classificação: Sobrepeso, Risco de doenças: Moderado"
    elif 30 <= imc <= 34.9:
        return "Classificação: Obesidade Grau I, Risco de doenças: Alto"
    elif 35 <= imc <= 39.9:
        return "Classificação: Obesidade Grau II, Risco de doenças: Muito Alto"
    else:
        return "Classificação: Obesidade Grau III, Risco de doenças: Extremamente Alto"

print("===== Calculo e classifiação de IMC: =====\n")

peso = float(input("Digite o seu peso (kg): "))
altura = float(input("Digite a sua altura (m): "))

imc = calculo_imc(peso, altura)
classificacao = classificacao_imc(imc)

print(f"O seu índice de massa corporal é {imc:.2f}, portanto a sua {classificacao}.")

"""
Contar números pares até N
• Escreva um programa que receba um número N e conte quantos números pares existem
de 1 até N
"""
print("===== Contar números pares até N: =====\n")

numero = int(input("Digite o um numero: "))
par = 0
impar = 0

for i in range(1, numero + 1):
  if i % 2 ==  0:
    par += 1
  else:
    impar += 1

print(f"o numero {numero} possui {par} elementos par e {impar} elementos impar\n")

"""
Senha com tentativas
• Escreva um programa que solicite uma senha e permita até 3 tentativas. Se acertar, exiba
“Acesso permitido”, senão “Bloqueado”.
"""
print("===== Senha com tentativas: =====\n")

senha = "1234"
limite_tentativas = 3
tentativa = 1

while tentativa <= 3:
  user_tentativa = input("Digite a sua senha: ")
  if senha == user_tentativa:
    print("Acesso concedido com sucesso! \n")
    break
  elif tentativa <= 2:
    print(f"Acesso negado, senha incorreta! te resta {limite_tentativas - tentativa } tentativa(s)\n")
    tentativa += 1
  else:
    print("Acesso bloqueado, contatar o suporte\n")
    break

"""
Somatório até zero
• Escreva um programa que leia números até o usuário digitar 0. Ao final, exiba a soma dos
números digitados.
• Exemplo: usuário digita 3 = operação 3+0(sendo zero o total anterior)
usuário digita 5 = operação 5 + 3(sendo 3 o valor do total anterior)
• Usuário digita 7 = operação 7 + 8(sendo 8 o valor do total anterior)
"""
print("===== Somatório até zero: =====\n")

soma = 0

while True:
  user_num = int(input("Digite um numero inteiro: "))
  if user_num == 0:
    break

"""
Menu interativo
• Crie um menu com opções:
o 1 → Somar dois números
o 2 → Tabuada
o 0 → Sair
Use while para repetir até escolher sair.
o O programa deve ao ser selecionada a opção 1, solicitar que o usuário digite os
valores e retornar o total da soma
o O programa deve quando informado a opção 2, solicitar o número para a
tabuada e retornar para o usuário a tabuada correspondente ao número
informado:
5 X 1 = 5
5 x 2 = 10
5 x 3 = 15
o Ao finalizar o programa exibir uma mensagem ao usuário:
“Obrigada por utilizar o app EDN cálculos, se precisar de um novo cálculo volte a
nos procurar.”
"""
def soma(numero_1, numero_2):
  resultado = numero_1 + numero_2
  return resultado

def tabuada(tabuada_numero):
    resultados = []
    for i in range(1, 11):
        resultados.append(f"{tabuada_numero} X {i} = {tabuada_numero * i}")
    return "\n".join(resultados)

while True:
  print("\n===== Menu interativo: =====\n")

  menu = int(input(" 1) Soma de dois números\n 2) Tabuada\n 3) Sair \nDigite o numero da opção desejada: "))

  if menu == 1:
    n1 = float(input("Digiite o primeiro valor: "))
    n2 = float(input("Digite o segundo valor: "))
    print(f"A soma entre {n1} + {n2} = {soma(n1, n2)}")
  elif menu == 2:
    tabuada_desejada = int(input("Digite qual tabuada vc almeja: "))
    print(tabuada(tabuada_desejada))
  elif menu == 3:
    print("Obrigada por utilizar o app EDN cálculos, se precisar de um novo cálculo volte a nos procurar.")
    break
  else:
    print("Opção não identificada, tente novamente")

"""
Crie um programa que:
• Permita cadastrar alunos com nome e idade.
• Armazene os dados em uma lista.
• Exiba um menu com opções:
o 1 → Cadastrar aluno
o 2 → Listar alunos cadastrados
o 0 → Sair
• Use variáveis, if/else e laços de repetição para controlar o fluxo.
"""

alunos_cadastrados = []

while True:
  print("\n===== Sistema de cadatro: =====\n")

  navbar = int(input(" 1) Cadastrar Aluno:\n 2) Listar Alunos Cadastrados:\n 0) Sair \nDigite a opção desejada:"))

  if navbar == 1:
    nome = input("Digite o nome do aluno: ")
    idade = input("Digite a idade do aluno: ")
    alunos_cadastrados.append(f"Aluno: {nome}, Idade: {idade}\n")
  elif navbar == 2:
    print(f"LISTA DE ALUNOS CADASTRADOS:{(alunos_cadastrados)}")
  elif navbar == 0:
    print("Muito obrigado por utilizar o sistema")
    break
  else:
    print("Opção invalida, tente novamente!")

"""
1. Função Simples de Saudação
Crie uma função chamada saudacao que imprima uma mensagem de boas-vindas.
Chame a função para exibir a mensagem.
"""
def saudacao(nome):
  return f"Olá {nome}, seja bem vindo a Escola da nuvem, é um prazer ter você como aluno!!\n"

print("===== Sudação simples: =====\n")

nome = input("Digite o seu nome")

print(saudacao(nome))

"""
2. Função que Retorna um Valor
Crie uma função soma que receba dois números e retorne a soma deles.
Imprima o resultado da função
"""
def soma(n1, n2):
  return n1 + n2

print("===== Soma entre 2 valores: =====\n")

n1 = float(input("Digte o primeiro valor: "))
n2 = float(input("Digite o segundo valor: "))

print(f"A soma entre {n1} + {n2} = {soma(n1, n2)}")

"""
� Enunciado:
Os servidores de um Data Center possuem sensores automáticos que medem a
temperatura interna em graus Fahrenheit (°F). No entanto, a equipe de monitoramento do
Brasil precisa ler esses dados em graus Celsius (°C).
Crie um programa em Python que tenha uma função chamada converter_para_celsius.
Essa função deve receber a temperatura em Fahrenheit como parâmetro, calcular a
conversão e retornar o valor em Celsius. No programa principal, solicite a temperatura ao
usuário, chame a função e exiba o resultado formatado com duas casas decimais.
● Fórmula de conversão: C = (F - 32) x 5/9
"""
def  converter_para_celsius(temperatura_fahrenheit):
  celcius = (temperatura_fahrenheit - 32) * 5 / 9
  return celcius

print("===== O Conversor de Temperatura do Data Center =====\n")

fahrenheit = float(input("Digite a temperatura em Fahrenheit: "))

print(f"{fahrenheit:.2f} F° = {converter_para_celsius(fahrenheit):.2f} °C\n")

"""
Uma empresa de suporte técnico N1 atende três tipos de demandas de clientes: "sistema",
"rede" ou "hardware". O tempo limite de atendimento (SLA) muda de acordo com o setor
afetado.
Crie um programa que tenha uma função chamada verificar_sla. Ela deve receber o nome
do setor afetado, tratar o texto para evitar erros de digitação e retornar a string com o
tempo padrão de atendimento. Se o setor digitado for inválido, deve retornar "Setor
desconhecido".
● Regras de Negócio:
○ Se for "sistema" -> Retornar "SLA: 4 horas (Prioridade Média)"
○ Se for "rede" -> Retornar "SLA: 2 horas (Prioridade Alta)"
○ Se for "hardware" -> Retornar "SLA: 24 horas (Prioridade Baixa)"
"""
def verificar_sla(setor):
  tratar_texto = setor.lower()
  if tratar_texto == "sistema":
    return "SLA: 4 horas (Prioridade Média)"
  elif tratar_texto == "rede":
    return "SLA: 2 horas (Prioridade Alta)"
  elif tratar_texto == "hardware":
    return "SLA: 24 horas (Prioridade Baixa)"
  else:
    return  "Setor desconhecido"

setor_afetado = input("Digite o nome do setor afetado: ")

print(verificar_sla(setor_afetado))

"""
Para monitorar a qualidade do link de internet de uma filial, o sistema de suporte realizou 4
testes automáticos de resposta de rede (Ping), medidos em milissegundos (ms).
Crie um programa com duas funções que trabalhem juntas:
1. A primeira função deve se chamar calcular_media_ping. Ela recebe a lista de testes,
soma todos os valores, divide pela quantidade de testes e retorna a média
aritmética calculada.
2. A segunda função deve se chamar avaliar_conexão. Ela recebe o número da média
calculado pela primeira função. Se a média for menor ou igual a 50ms, ela retorna
a mensagem "Conexão Estável". Caso contrário, retorna "Aviso: Conexão instável
ou sob alta carga".
"""
def calcular_media_ping(lista_testes):
  if not lista_testes:
    return 0
  soma = sum(lista_testes)
  quantidade = len(lista_testes)
  return soma / quantidade

def avaliar_conexao(media):
  if media <= 50:
    return f"Média de ping: {media}, Status: Conexão Estável"
  else:
    return f"Média de ping: {media}, Status: Aviso: Conexão instável ou sob alta carga"

print("===== Monitoramento de Qualidade: =====\n")

lista_ping = []

while True:
  menu = int(input("MENU INTERATIVO \n 1) Registrar Ping\n 2) Sair \nDigite a opção desejada: "))

  if menu == 1:
    ping = float(input("Digite o Ping: "))
    lista_ping.append(ping)
  elif menu == 2:
    break
  else:
    print("Opção invalida")

media = calcular_media_ping(lista_ping)

print(avaliar_conexao(media))

"""
� Desafio 3 (Nível Avançado): Sistema de Biblioteca Comunitária (Para os grupos que
querem ir além e construir um projeto mais elaborado)
O Problema: Desenvolver um sistema interativo pelo terminal para gerenciar o acervo e os
empréstimos de um espaço cultural ou biblioteca comunitária.
Requisitos do Sistema:
1. Menu Interativo: O programa deve rodar em um loop (while) exibindo um menu de
opções: [1] Cadastrar Livro, [2] Listar Acervo, [3] Emprestar
Livro, [4] Devolver Livro, [0] Sair.
2. Estrutura de Dados: Utilizar listas e dicionários para armazenar as informações.
Exemplo: {'titulo': 'Quarto de Despejo', 'autor': 'Carolina
Maria de Jesus', 'disponivel': True}.
3. Validações Lógicas: O sistema não pode permitir o empréstimo de um livro que já
está com o status disponivel: False. Ao devolver, o status deve voltar para
True.
4. Mensagens: O sistema deve dar feedbacks claros para o usuário (ex: "Livro
cadastrado com sucesso!", "Este livro já está emprestado").
"""
def cadastrar_livro(usuario, senha, livro, autor):
  usuario_permitido = "Camila Cleane"
  senha_permitida = "EscolaDaNuvem1234"

  if usuario == usuario_permitido and senha == senha_permitida:
    for item in acervo:
      if item['titulo'].lower() == livro.lower() and item['autor'].lower() == autor.lower():
        return "Já possuimos este livro em nosso acervo, por favor cadastre outro livro para não termos duplicidade"
      else:
        novo_livro = {
            'titulo': livro,
            'autor': autor,
            'disponivel': True
            }
        acervo.append(novo_livro)
        return "Livro cadastrado com sucesso!"
  else:
    return "Acesso negado, login ou senha está incorreto!"

acervo = []

while True:
  menu = int(input("==== MENU INTERATIVO: =====\n\n 1-) Cadastrar Livro:\n 2-) Listar Acervo:\n 3-) Emprestar Livro:\n 4-) Devolver Livro:\n 0-) Sair: \nDigite a opção:"))
  if menu == 1:
    print("Sistema de Login a Blibioteca EDN: \n")
    user = input("Usuario: ")
    password = input("Senha: ")
    livro = input("Informe o livro para cadastramento:")
    autor = input("Qual o nome do autor: ")
    print(cadastrar_livro(user, password, livro, autor))

  elif menu == 0:
    print("Obrigado por utilizar o Sistema de Biblioteca Comunitária EDN")
    break
  else:
    print("Opção invalida, tente novamente!\n")

livros = []

def exibir_menu():
    print("Sistema da biblioteca comunitária EDN")
    print("1- Cadastrar Livro")
    print("2- Listar Acervo da biblioteca")
    print("3- Emprestar Livro")
    print("4- Devolver Livro")
    print("0- Sair e finalizar programa")

while True:
    exibir_menu()
    opcao = input("Escolha uma opção: ").strip()

    if opcao == "1":
        titulo = input("\nDigite o título do livro: ").strip()
        autor = input("Digite o autor do livro: ").strip()
        if not titulo or not autor:
            print("Título e autor são obrigatórios!")
            continue
        livro = {'titulo': titulo, 'autor': autor, 'disponivel': True}
        livros.append(livro)
        print(f"Livro '{titulo}' cadastrado com sucesso!")

    elif opcao == "2":
        print("\nACERVO DA BIBLIOTECA:")
        if not livros:
            print("O acervo está vazio no momento.")
        else:
            for i, livro in enumerate(livros, 1):
                status = " Disponível" if livro['disponivel'] else "Emprestado"
                print(f"{i:2d}. {livro['titulo']} - {livro['autor']} | {status}")

    elif opcao == "3":
        if not livros:
            print("Não há livros cadastrados no momento.")
            continue
        titulo = input("\nDigite o título do livro que deseja emprestar: ").strip()
        encontrado = False
        for livro in livros:
            if livro['titulo'].lower() == titulo.lower():
                encontrado = True
                if livro['disponivel']:
                    livro['disponivel'] = False
                    print(f"Livro '{livro['titulo']}' emprestado com sucesso!")
                else:
                    print(f" O livro '{livro['titulo']}' já está emprestado.")
                break
        if not encontrado:
            print("Livro não encontrado no acervo.")

    elif opcao == "4":
        if not livros:
            print("Não há livros cadastrados.")
            continue
        titulo = input("\nDigite o título do livro que deseja devolver: ").strip()
        encontrado = False
        for livro in livros:
            if livro['titulo'].lower() == titulo.lower():
                encontrado = True
                if not livro['disponivel']:
                    livro['disponivel'] = True
                    print(f"Livro '{livro['titulo']}' devolvido com sucesso!")
                else:
                    print(f"O livro '{livro['titulo']}' já está disponível.")
                break
        if not encontrado:
            print("Livro não encontrado no acervo.")

    elif opcao == "0":

        print("Até a próxima!")
        break

    else:
        print("Opção inválida! escolha uma opção de 0 a 4.")

    input("\nPressione Enter para continuar.....")

"""
PROJETO FINAL, TECNOLOGIA PARA INICIANTES, TURMA 2, ESCOLA DA NUVEM

PARTICIPANTES:
João Vitor da Silva Moreno
Antonia Neide Magalhães
Luan Freitas Coelho Vieira

� Desafio 3 (Nível Avançado): Sistema de Biblioteca Comunitária (Para os grupos que
querem ir além e construir um projeto mais elaborado)
O Problema: Desenvolver um sistema interativo pelo terminal para gerenciar o acervo e os
empréstimos de um espaço cultural ou biblioteca comunitária.
Requisitos do Sistema:
1. Menu Interativo: O programa deve rodar em um loop (while) exibindo um menu de
opções: [1] Cadastrar Livro, [2] Listar Acervo, [3] Emprestar
Livro, [4] Devolver Livro, [0] Sair.
2. Estrutura de Dados: Utilizar listas e dicionários para armazenar as informações.
Exemplo: {'titulo': 'Quarto de Despejo', 'autor': 'Carolina
Maria de Jesus', 'disponivel': True}.
3. Validações Lógicas: O sistema não pode permitir o empréstimo de um livro que já
está com o status disponivel: False. Ao devolver, o status deve voltar para
True.
4. Mensagens: O sistema deve dar feedbacks claros para o usuário (ex: "Livro
cadastrado com sucesso!", "Este livro já está emprestado").
"""
from datetime import date
biblioteca = []
usuarios = []
historico = []

def acesso_adm(user, password):
  administrador = "Camilla Cleanne"
  senha = "EscolaDaNuvem1234"
  if user == administrador and senha == password:
    return True
  else:
    return False

def cadastrar_livro():
  codigo = input("Código do livro: ")
  titulo = input("Título: ")
  autor = input("Autor: ")

  for livro in biblioteca:
      if livro["codigo"] == codigo:
          print("❌ Já existe um livro com esse código.")
          return
  livro = {
      "codigo": codigo,
      "titulo": titulo,
      "autor": autor,
      "disponivel": True,
      "emprestado_para": None
  }
  biblioteca.append(livro)
  print("✅ Livro cadastrado com sucesso!")

def listar_acervo():
  if not biblioteca:
      print("Nenhum livro cadastrado.")
      return
  print("\n===== ACERVO =====")
  for livro in biblioteca:
      status = "Disponível"
      if not livro["disponivel"]:
          status = f"Emprestado para {livro['emprestado_para']} na data de {livro['emprestimo_data']}"
      print(f"""
      Código: {livro['codigo']}
      Título: {livro['titulo']}
      Autor: {livro['autor']}
      Status: {status}
      """)

def cadastrar_usuario():
  nome = input("Nome do usuário: ")
  cpf = input("CPF do usuário: ")
  telefone = input("Número de contato: ")
  email = input("Email do usuário: ")
  endereco = input("Endereço do usuario: ")
  for usuario in usuarios:
      if usuario["nome"].lower() == nome.lower() or usuario["cpf"] == cpf:
          print("❌ Usuário já cadastrado.")
          return
  usuarios.append({
      'nome': nome,
      'cpf': cpf,
      'telefone': telefone,
      'email': email,
      'endereco': endereco
  })
  print("✅ Usuário cadastrado com sucesso!")

def emprestar_livro():
  codigo = input("Código do livro: ")
  nome_do_livro = input("Nome do Livro: ")
  nome_usuario = input("Nome do usuário: ")
  cpf_usuario = input("Cpf do usuário: ")
  usuario_existe = False
  cpf_existente = False

  for usuario in usuarios:
      if usuario["nome"].lower() == nome_usuario.lower() or usuario["cpf"] == cpf_usuario:
        usuario_existe = True
        cpf_existente = True
      else:
        print("❌ Usuário não encontrado.")
        return
  for livro in biblioteca:
      if livro["codigo"] == codigo or livro["titulo"].lower() == nome_do_livro.lower():
          if not livro["disponivel"]:
              print("❌ Livro já emprestado.")
              return
          livro["disponivel"] = False
          livro["emprestado_para"] = nome_usuario
          livro["emprestimo_data"] = date.today()
          historico.append(

              f"{nome_usuario} pegou '{livro['titulo']}'"
          )
          print("✅ Empréstimo realizado.")
          return
  print("❌ Livro não encontrado.")

def devolver_livro():
  codigo = input("Código do livro: ")
  for livro in biblioteca:
      if livro["codigo"] == codigo:
          if livro["disponivel"]:
              print("❌ Este livro já está disponível.")
              return
          usuario = livro["emprestado_para"]
          historico.append(f"{usuario} devolveu '{livro['titulo']}'")
          livro["disponivel"] = True
          livro["emprestado_para"] = None
          print("✅ Livro devolvido.")
          return
  print("❌ Livro não encontrado.")

def pesquisar_livro():
  termo = input("Digite parte do título: ").lower()
  encontrados = False
  for livro in biblioteca:
      if termo in livro["titulo"].lower():
          print(f"""
          Código: {livro['codigo']}
          Título: {livro['titulo']}
          Autor: {livro['autor']}
          """)
          encontrados = True
  if not encontrados:
      print("Nenhum livro encontrado.")

def mostrar_historico():
  if not historico:
      print("Nenhuma movimentação registrada.")
      return
  print("\n===== HISTÓRICO =====")
  for registro in historico:
      print(registro)

def listar_usuarios():
  print(f"""
  ====================
  LISTAGEM DE USUÁRIOS
  ====================
  """)
  for usuario in usuarios:
    print(f"""
      Nome: {usuario['nome']}
      CPF: {usuario['cpf']}
      Telefone: {usuario['telefone']}
      E-mail: {usuario['email']}
      Endereço: {usuario['endereco']}
      """)
  return
while True:
  print("""
  ===================================
  LOGIN DA BIBLIOTECA COMUNITÁRIA EDN
  ===================================
  login administrativo:
  """)
  user = input("Usuario: ")
  password = input("Senha: ")
  acesso = acesso_adm(user, password)
  if acesso == True:
    break
  else:
    print("Acesso Negado, Login ou senha incorreto, tente novamente!")

while True:
  print("""
=============================
 BIBLIOTECA COMUNITÁRIA EDN
=============================
1 - Cadastrar Livro
2 - Listar Acervo
3 - Cadastrar Usuário
4 - Emprestar Livro
5 - Devolver Livro
6 - Pesquisar Livro
7 - Histórico
8 - Listar Usuários
0 - Sair
=============================
""")
  opcao = input("Escolha uma opção: ")
  if opcao == "1":
    cadastrar_livro()
  elif opcao == "2":
    listar_acervo()
  elif opcao == "3":
    cadastrar_usuario()
  elif opcao == "4":
    emprestar_livro()
  elif opcao == "5":
    devolver_livro()
  elif opcao == "6":
    pesquisar_livro()
  elif opcao == "7":
    mostrar_historico()
  elif opcao == "8":
    listar_usuarios()
  elif opcao == "0":
    listar_usuarios()
    break
  else:
    print("❌ Opção inválida.")